#pragma once

/// @file Buttons.hxx
/// @brief Buttons enumeration

namespace Core4
{
    /// Buttons enumeration container.
    struct Buttons
    {
        /// Buttons enumeration type.
        enum Type
        {
            MouseLB = 0,
            MouseRB,
            MouseMB,
            MWheelUp,
            MWheelDown,
            Backspace,
            Tab,
            Enter,
            Shift,
            Control,
            Alt,
            Pause,
            CapsLock,
            Escape,
            Space,
            PageUp,
            PageDown,
            End,
            Home,
            Left,
            Up,
            Right,
            Down,
            PrintScreen,
            Insert,
            Delete,
            Zero,
            One,
            Two,
            Three,
            Four,
            Five,
            Six,
            Seven,
            Eight,
            Nine,
            A,
            B,
            C,
            D,
            E,
            F,
            G,
            H,
            I,
            J,
            K,
            L,
            M,
            N,
            O,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            W,
            X,
            Y,
            Z,
            Numpad0,
            Numpad1,
            Numpad2,
            Numpad3,
            Numpad4,
            Numpad5,
            Numpad6,
            Numpad7,
            Numpad8,
            Numpad9,
            Multiply,
            Add,
            Separator,
            Subtract,
            Decimal,
            Divide,
            F1,
            F2,
            F3,
            F4,
            F5,
            F6,
            F7,
            F8,
            F9,
            F10,
            NumLock,
            ScrollLock,
            Unknown
        }; // enum Type
    }; // struct Buttons
} // namespace Core4
